### ISSUE TITLE
What license do you expect for this code?

### ISSUE THREAD

**Issue by indenkun** [jonocarroll/VolunteerVignettes#6]
What license do you expect for this code?

I thought it was very interesting code and took the liberty of forking it, modifying some currently unused functions in the function to make it easier for me to use and package it(https://github.com/indenkun/VolunteerVignettes), but when I looked closely at your original code, I could not find a license anywhere.

I would appreciate it if you could let me know.

Sincerely yours

**Comment by jonocarroll** [comment]
Hi, I'm fine with the MIT license on this, which doesn't strictly require you to share any improvements with me. I added the relevant file to this repo.

I would ask you to use the following attribution in `DESCRIPTION`, please

```
person("Jonathan", "Carroll", email = "rpkg@jcarroll.com.au", role = c("aut"), comment = c(ORCID = "0000-0002-1404-5264"))
```

Cheers, and best wishes with the project.

**Comment by indenkun** [comment]
Thank you for your response and for adding the license information.

I will put the information you provided to good use.
